### ISSUE TITLE
one more crash：JSONPreview 的 preview(_ json: String, style: HighlightStyle = .default, completion: (() -> Void)? = nil)

### ISSUE THREAD

**Issue by mxh-mo** [rakuyoMo/JSONPreview#10] opened 2023-10-19 07:50 UTC
<img width="2411" alt="企业微信截图_4b3718b1-a844-4cca-96be-c7df52633f4e" src="https://github.com/RakuyoKit/JSONPreview/assets/16602188/392fe8fa-88d0-4ee4-877d-cd244ca6bc99">

**Comment by mxh-mo** [comment] 2023-10-19 07:52
"{\"tinyId\":\"144115529973900856\",\"originalAccountModel\":{\"accountIdType\":0,\"authKeyType\":0,\"authKey\":\"-xsDf6nk76jKc8Gogrb54g.M\",\"isVisitor\":false,\"accountId\":\"2873916004\"},\"ticketModel\":{\"a2ExpireTime\":1700119148,\"a2Ticket\":\"3216c2ec48d5b894b423601efd24ca8c694a6b1a57550022f658825f0a401e7d5684807871fd19ca8f1626d2c8038b35bf98d0c87febce6aeb91d846112ae4796e949845a2be6d0c\"},\"uid\":\"4999561028\",\"accountStatus\":0}"

**Comment by mxh-mo** [comment] 2023-10-19 07:53
@rakuyoMo  i provided json string, could you debug this issue first

**Comment by mxh-mo** [comment] 2023-10-19 07:58
Use it! Is it too dangerous ？
<img width="525" alt="企业微信截图_ebeb8c54-e3dd-4e09-9e10-e0cf0a023e0f" src="https://github.com/RakuyoKit/JSONPreview/assets/16602188/6831ec8d-4ff3-41cd-812f-b1a54407375a">

**Comment by rakuyoMo** [comment] 2023-10-20 09:40
> @rakuyoMo i provided json string, could you debug this issue first

Okay, I'll troubleshoot this first.

BTW, This isn't the json for  [#9](https://github.com/RakuyoKit/JSONPreview/issues/9)?

**Comment by rakuyoMo** [comment] 2023-10-20 09:55
<img width="1551" alt="image" src="https://github.com/RakuyoKit/JSONPreview/assets/16268770/6cd45c03-95ac-437a-9876-7977c4feb35e">

This json displays fine in my demo, have you tried to reproduce your problem using the demo in your project?


The current information is not enough for me to troubleshoot the issue, but I noticed in your screenshot that the `self` variable has a value of nil, or you should check the method or timing of how you initialize or use the `JSONPreview` instance. Or provide me more information about it. It would be better if you can directly provide a minimized demo that reproduces the problem.

**Comment by mxh-mo** [comment] 2023-10-27 01:57
This is not mandatory

**Comment by rakuyoMo** [comment] 2023-10-27 08:52
I have an assumption:

I guess you are using JSONPreview in combination with a list view (UITableView or UICollectiontView).

If this is the case, then it is possible to have a `decorator` of `nil` when sliding fast, or in other cases, perhaps in the `decorator`'s didSet method.

`decorator` is assigned -> Cell of JSONPreview instance‘s superview is released -> `decorator` is nil in `decorator`'s didSet method.

**Comment by rakuyoMo** [comment] 2023-10-27 09:43
@mxh-mo I committed some code on the [develop branch](https://github.com/RakuyoKit/JSONPreview/commit/27cc814331dedbe348ac374b21eb59d63517f0f1), you can try switching to that branch and see if the crash still occurs.

But I'm more concerned about whether the behavior of the JSONPreview object meets your expectations if the crash goes away. I am very concerned about that.

I will close the issue as well as [#9](https://github.com/RakuyoKit/JSONPreview/issues/9) and you can reply under this question if the issue is not resolved.

If the fix causes other issues, you can open a new issue.

Have a nice life.

**Closed as completed** 2023-10-27 09:45 UTC
Labels: bug

**Comment by mxh-mo** [comment] 2023-11-23 03:05
We fixed code like this:
<img width="951" alt="企业微信截图_eb00394c-6015-485c-a2af-93ce3e7cc941" src="https://github.com/RakuyoKit/JSONPreview/assets/16602188/7332002a-736b-4f82-a7af-34829794b42a">

**Comment by rakuyoMo** [comment] 2023-11-23 05:35
The `highlight(_: judgmentValid: style:)` method will return `nil` when the `json` is illegal.

Similar processing has been added to the develop branch. It looks like we can release the change.

**Comment by mxh-mo** [comment] 2023-11-28 01:21
but is still crash, then we changed like this:
<img width="983" alt="image" src="https://github.com/RakuyoKit/JSONPreview/assets/16602188/bf3bccf3-66ee-4468-b93d-07268c9557f6">
self should be use on main queue, too
